export const ASSERTION_TYPES = {
  STATUS_CODE: 'STATUS_CODE',
  RESPONSE_TIME: 'RESPONSE_TIME',
  BODY_CONTAINS: 'BODY_CONTAINS',
  HEADER_EXISTS: 'HEADER_EXISTS',
  JSON_PATH: 'JSON_PATH',
};

export default ASSERTION_TYPES;
